ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_dark_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_light_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS photo_processing BOOLEAN DEFAULT FALSE;
