-- ============================================================
-- Migration 002: Onboarding v2 — responsible-first flow, invite-only players
-- Run in Supabase SQL Editor
-- ============================================================

-- Add subscription_tier to users
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_tier TEXT DEFAULT 'basic';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'users_subscription_tier_check'
    ) THEN
        ALTER TABLE users ADD CONSTRAINT users_subscription_tier_check
            CHECK (subscription_tier IN ('basic', 'premium'));
    END IF;
END$$;

-- Remove old default for onboarding_state (NULL = fresh user)
ALTER TABLE users ALTER COLUMN onboarding_state DROP DEFAULT;

-- Add pair_code (6-char alphanumeric, generated by Responsible)
ALTER TABLE partnerships ADD COLUMN IF NOT EXISTS pair_code VARCHAR(8);

-- Add player_name (name entered by Responsible before generating link)
ALTER TABLE partnerships ADD COLUMN IF NOT EXISTS player_name TEXT;

-- Unique index on pair_code (NULLs allowed for legacy records)
CREATE UNIQUE INDEX IF NOT EXISTS idx_partnerships_pair_code
    ON partnerships(pair_code)
    WHERE pair_code IS NOT NULL;
